# This is the configuration file for SetHome v0.1.0.
# Contact me at https://viral32111.com/contact if you need help.

# The configuration for experience usage
experience:

    # Should experience be required and consumed for players teleporting.
    enabled: true

    # The amount of experience that will be consumed on teleport.
    # If a player has less than this amount, they will not be able to teleport.
    amount: 5

    # The configuration for distance-based experience usage
    scale:

        # Should the amount of experience consumed scale with the distance of the teleport.
        # If this is enabled, the experience -> amount option is ignored.
        enabled: false

        # The scale factor for amount of experience that will be consumed based on teleport distance.
        # For example, with a factor of 0.2 and a distance of 100, the amount consumed would be 20.
        factor: 0.2
